"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['PSPEWC.py']
APP_NAME = "PSPEWC"
DATA_FILES = ['EWCcontroller.py', 'EWCnetworking.py']
OPTIONS = {
	'argv_emulation': True,
	'iconfile':'icons.icns',
	'plist': {
		'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
		'LSUIElement': True,
		'CFBundleIdentifier': "com.jacques.osx.PSPEWC",
		'CFBundleVersion': "0.3.1",
        'CFBundleShortVersionString': "0.3.1",
        'NSHumanReadableCopyright': "Copyright 2017, Jacob Gaffney, All Rights Reserved"
	},
	'packages': ['rumps'],
}

setup(
	name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
